# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1496, 869)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_header.setStyleSheet("QFrame{\n"
"    border-bottom: 1px solid #000;\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.main_header.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tittle_bar_container = QtWidgets.QFrame(self.main_header)
        self.tittle_bar_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tittle_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar_container.setObjectName("tittle_bar_container")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tittle_bar_container)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.left_menu_toggle = QtWidgets.QFrame(self.tittle_bar_container)
        self.left_menu_toggle.setMinimumSize(QtCore.QSize(50, 0))
        self.left_menu_toggle.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_menu_toggle.setStyleSheet("QFrame{\n"
"    background-color: #000;\n"
"}\n"
"QPushButton{\n"
"    padding: 5px 10px;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_menu_toggle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_menu_toggle_btn = QtWidgets.QPushButton(self.left_menu_toggle)
        self.left_menu_toggle_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.left_menu_toggle_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_menu_toggle_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.left_menu_toggle_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_menu_toggle_btn.setIcon(icon)
        self.left_menu_toggle_btn.setIconSize(QtCore.QSize(24, 24))
        self.left_menu_toggle_btn.setObjectName("left_menu_toggle_btn")
        self.horizontalLayout_4.addWidget(self.left_menu_toggle_btn)
        self.horizontalLayout_6.addWidget(self.left_menu_toggle)
        self.tittle_bar = QtWidgets.QFrame(self.tittle_bar_container)
        self.tittle_bar.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.tittle_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tittle_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar.setObjectName("tittle_bar")
        self.label_6 = QtWidgets.QLabel(self.tittle_bar)
        self.label_6.setGeometry(QtCore.QRect(12, 12, 1371, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.tittle_bar)
        self.horizontalLayout_2.addWidget(self.tittle_bar_container)
        self.top_right_btns = QtWidgets.QFrame(self.main_header)
        self.top_right_btns.setMaximumSize(QtCore.QSize(150, 16777215))
        self.top_right_btns.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.restoreButton = QtWidgets.QPushButton(self.top_right_btns)
        self.restoreButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.restoreButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreButton.setIcon(icon1)
        self.restoreButton.setIconSize(QtCore.QSize(24, 24))
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout_3.addWidget(self.restoreButton)
        self.minimizeButton = QtWidgets.QPushButton(self.top_right_btns)
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon2)
        self.minimizeButton.setIconSize(QtCore.QSize(24, 24))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_3.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.top_right_btns)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon3)
        self.closeButton.setIconSize(QtCore.QSize(24, 24))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.horizontalLayout_2.addWidget(self.top_right_btns)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_side_menu.sizePolicy().hasHeightForWidth())
        self.left_side_menu.setSizePolicy(sizePolicy)
        self.left_side_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.left_side_menu.setMaximumSize(QtCore.QSize(166, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.left_side_menu.setFont(font)
        self.left_side_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.left_side_menu.setStyleSheet("QFrame{\n"
"    background-color: #000;\n"
"}\n"
"QPushButton{\n"
"    padding: 20px 10px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(0, 92, 157);\n"
"    border-bottom: 2px solid rgb(255, 165, 24);\n"
"}")
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.formLayout_2 = QtWidgets.QFormLayout(self.left_side_menu)
        self.formLayout_2.setContentsMargins(3, 0, 0, 0)
        self.formLayout_2.setSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.left_menu_top_buttons = QtWidgets.QFrame(self.left_side_menu)
        self.left_menu_top_buttons.setMinimumSize(QtCore.QSize(0, 103))
        self.left_menu_top_buttons.setMaximumSize(QtCore.QSize(16777215, 124))
        self.left_menu_top_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_top_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_top_buttons.setObjectName("left_menu_top_buttons")
        self.formLayout_4 = QtWidgets.QFormLayout(self.left_menu_top_buttons)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(3, 0, 0, 0)
        self.formLayout_4.setSpacing(0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.accounts_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accounts_button.sizePolicy().hasHeightForWidth())
        self.accounts_button.setSizePolicy(sizePolicy)
        self.accounts_button.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.accounts_button.setFont(font)
        self.accounts_button.setStyleSheet("background-image: url(:/icons/icons/cil-user.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.accounts_button.setObjectName("accounts_button")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.accounts_button)
        self.home_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.home_button.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.home_button.setFont(font)
        self.home_button.setStyleSheet("background-image: url(:/icons/icons/cil-home.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.home_button.setObjectName("home_button")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.home_button)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.left_menu_top_buttons)
        self.left_menu_notes = QtWidgets.QFrame(self.left_side_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_menu_notes.sizePolicy().hasHeightForWidth())
        self.left_menu_notes.setSizePolicy(sizePolicy)
        self.left_menu_notes.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.left_menu_notes.setFont(font)
        self.left_menu_notes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_notes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_notes.setObjectName("left_menu_notes")
        self.formLayout = QtWidgets.QFormLayout(self.left_menu_notes)
        self.formLayout.setContentsMargins(3, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.notes_button = QtWidgets.QPushButton(self.left_menu_notes)
        self.notes_button.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.notes_button.setFont(font)
        self.notes_button.setStyleSheet("background-image: url(:/icons/icons/cil-notes.png);\n"
"background-repeat: none;\n"
"padding-left: 30px;\n"
"background-position: center left;")
        self.notes_button.setAutoDefault(False)
        self.notes_button.setDefault(False)
        self.notes_button.setFlat(False)
        self.notes_button.setObjectName("notes_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.notes_button)
        self.newnoteBtn = QtWidgets.QPushButton(self.left_menu_notes)
        self.newnoteBtn.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.newnoteBtn.setFont(font)
        self.newnoteBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newnoteBtn.setStyleSheet("background-image: url(:/icons/icons/cil-library-add.png);\n"
"background-repeat: none;\n"
"padding-left: 30px;\n"
"background-position: center left;")
        self.newnoteBtn.setAutoDefault(False)
        self.newnoteBtn.setDefault(False)
        self.newnoteBtn.setFlat(False)
        self.newnoteBtn.setObjectName("newnoteBtn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.newnoteBtn)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.left_menu_notes)
        self.frame = QtWidgets.QFrame(self.left_side_menu)
        self.frame.setMinimumSize(QtCore.QSize(66, 99))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settings_button = QtWidgets.QPushButton(self.frame)
        self.settings_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_button.sizePolicy().hasHeightForWidth())
        self.settings_button.setSizePolicy(sizePolicy)
        self.settings_button.setMinimumSize(QtCore.QSize(50, 0))
        self.settings_button.setStyleSheet("background-image: url(:/icons/icons/cil-settings.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.settings_button.setObjectName("settings_button")
        self.verticalLayout_2.addWidget(self.settings_button)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.frame)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1024, 768))
        self.stackedWidget.setAccessibleName("")
        self.stackedWidget.setAccessibleDescription("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setMinimumSize(QtCore.QSize(1024, 768))
        self.home_page.setStyleSheet("")
        self.home_page.setObjectName("home_page")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.home_page)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.home_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(461, 91))
        self.frame_2.setMaximumSize(QtCore.QSize(461, 91))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-image: url(images/emynote_360x90.png);\n"
"    border-radius: 30px;\n"
"    border: 1px solid rgb(255, 207, 0);\n"
"    background-position: center;\n"
"background-repeat:none;\n"
"   \n"
"}\n"
"QFrame:hover {\n"
"    border: 1px solid rgb(255, 225, 0);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.home_page)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setMinimumSize(QtCore.QSize(0, 0))
        self.login_page.setStyleSheet("")
        self.login_page.setObjectName("login_page")
        self.content = QtWidgets.QFrame(self.login_page)
        self.content.setGeometry(QtCore.QRect(260, 10, 481, 631))
        self.content.setMinimumSize(QtCore.QSize(481, 631))
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.login_area = QtWidgets.QFrame(self.content)
        self.login_area.setGeometry(QtCore.QRect(20, 60, 450, 550))
        self.login_area.setMaximumSize(QtCore.QSize(450, 550))
        self.login_area.setStyleSheet("border-radius: 10px;")
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")
        self.logo = QtWidgets.QFrame(self.login_area)
        self.logo.setGeometry(QtCore.QRect(50, 20, 360, 90))
        self.logo.setStyleSheet("background-image: url(Images/logo_360x90.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.avatar = QtWidgets.QFrame(self.login_area)
        self.avatar.setGeometry(QtCore.QRect(160, 110, 120, 120))
        self.avatar.setStyleSheet("QFrame {\n"
"    background-image: url(Images/avatar.png);\n"
"    border-radius: 60px;\n"
"    border: 10px solid rgb(255, 207, 0);\n"
"    background-position: center;\n"
"}\n"
"QFrame:hover {\n"
"    border: 10px solid rgb(255, 225, 0);\n"
"}\n"
"\n"
"")
        self.avatar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.avatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.avatar.setObjectName("avatar")
        self.lineEdit_user = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_user.setGeometry(QtCore.QRect(80, 240, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setAutoFillBackground(False)
        self.lineEdit_user.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);        \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_user.setInputMask("")
        self.lineEdit_user.setText("")
        self.lineEdit_user.setMaxLength(32)
        self.lineEdit_user.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_password = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_password.setGeometry(QtCore.QRect(80, 315, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_password.setMaxLength(16)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.checkBox_save_user = QtWidgets.QCheckBox(self.login_area)
        self.checkBox_save_user.setGeometry(QtCore.QRect(80, 390, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.checkBox_save_user.setFont(font)
        self.checkBox_save_user.setStyleSheet("QCheckBox {\n"
"    color:rgb(255, 255, 255)  \n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(135, 135, 135);\n"
"    \n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 205, 0);\n"
"    background-color: rgb(255, 255, 0);\n"
"}\n"
"QCheckBox::qlabel {\n"
"    color:#2BC1B8!important; }\n"
"\n"
"")
        self.checkBox_save_user.setObjectName("checkBox_save_user")
        self.pushButton_login = QtWidgets.QPushButton(self.login_area)
        self.pushButton_login.setGeometry(QtCore.QRect(80, 470, 280, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("QPushButton {    \n"
"\n"
"    background-color:rgb(255, 255, 127);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color:  rgb(239, 239, 239);\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.Login_reg = QtWidgets.QPushButton(self.login_area)
        self.Login_reg.setGeometry(QtCore.QRect(81, 526, 270, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Login_reg.setFont(font)
        self.Login_reg.setStyleSheet("QPushButton { \n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover { \n"
"    color: rgb(255, 255, 127);\n"
"}")
        self.Login_reg.setObjectName("Login_reg")
        self.frame_error = QtWidgets.QFrame(self.content)
        self.frame_error.setGeometry(QtCore.QRect(20, 20, 450, 38))
        self.frame_error.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_error.setStyleSheet("background-color: rgb(255, 85, 127);\n"
"border-radius: 5px;")
        self.frame_error.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setGeometry(QtCore.QRect(11, 11, 401, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color: rgb(35, 35, 35);")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.pushButton_close_pupup = QtWidgets.QPushButton(self.frame_error)
        self.pushButton_close_pupup.setGeometry(QtCore.QRect(419, 11, 20, 20))
        self.pushButton_close_pupup.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_close_pupup.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;    \n"
"    background-image: url(Images/cil-x.png);\n"
"    background-position: center;    \n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.pushButton_close_pupup.setText("")
        self.pushButton_close_pupup.setObjectName("pushButton_close_pupup")
        self.stackedWidget.addWidget(self.login_page)
        self.accounts_page = QtWidgets.QWidget()
        self.accounts_page.setMinimumSize(QtCore.QSize(667, 800))
        self.accounts_page.setObjectName("accounts_page")
        self.content_3 = QtWidgets.QFrame(self.accounts_page)
        self.content_3.setGeometry(QtCore.QRect(104, 10, 667, 679))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content_3.sizePolicy().hasHeightForWidth())
        self.content_3.setSizePolicy(sizePolicy)
        self.content_3.setMinimumSize(QtCore.QSize(667, 679))
        self.content_3.setStyleSheet("")
        self.content_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_3.setObjectName("content_3")
        self.login_area_4 = QtWidgets.QFrame(self.content_3)
        self.login_area_4.setGeometry(QtCore.QRect(12, 59, 647, 608))
        self.login_area_4.setMaximumSize(QtCore.QSize(647, 641))
        self.login_area_4.setStyleSheet("border-radius: 10px;")
        self.login_area_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area_4.setObjectName("login_area_4")
        self.logo_4 = QtWidgets.QFrame(self.login_area_4)
        self.logo_4.setGeometry(QtCore.QRect(160, 50, 191, 90))
        self.logo_4.setStyleSheet("background-image: url(Images/useraccount.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.logo_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_4.setObjectName("logo_4")
        self.avatar_4 = QtWidgets.QFrame(self.login_area_4)
        self.avatar_4.setGeometry(QtCore.QRect(30, 70, 121, 121))
        self.avatar_4.setStyleSheet("QFrame {\n"
"    background-image: url(Images/avatar.png);\n"
"    border-radius: 60px;\n"
"    border: 10px solid rgb(255, 207, 0);\n"
"    background-position: center;\n"
"}\n"
"QFrame:hover {\n"
"    border: 10px solid rgb(255, 225, 0);\n"
"}\n"
"\n"
"")
        self.avatar_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.avatar_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.avatar_4.setObjectName("avatar_4")
        self.loggedUser = QtWidgets.QLineEdit(self.login_area_4)
        self.loggedUser.setEnabled(False)
        self.loggedUser.setGeometry(QtCore.QRect(180, 150, 391, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.loggedUser.setFont(font)
        self.loggedUser.setAutoFillBackground(False)
        self.loggedUser.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);        \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.loggedUser.setInputMask("")
        self.loggedUser.setText("")
        self.loggedUser.setMaxLength(32)
        self.loggedUser.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.loggedUser.setObjectName("loggedUser")
        self.logoutBtn = QtWidgets.QPushButton(self.login_area_4)
        self.logoutBtn.setGeometry(QtCore.QRect(390, 240, 181, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logoutBtn.setFont(font)
        self.logoutBtn.setStyleSheet("QPushButton {    \n"
"\n"
"    background-color:rgb(255, 255, 127);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color:  rgb(239, 239, 239);\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.logoutBtn.setObjectName("logoutBtn")
        self.changepasBtn = QtWidgets.QPushButton(self.login_area_4)
        self.changepasBtn.setGeometry(QtCore.QRect(180, 240, 171, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.changepasBtn.setFont(font)
        self.changepasBtn.setStyleSheet("QPushButton {    \n"
"\n"
"    background-color:rgb(255, 255, 127);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color:  rgb(239, 239, 239);\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.changepasBtn.setObjectName("changepasBtn")
        self.user_id = QtWidgets.QLabel(self.login_area_4)
        self.user_id.setGeometry(QtCore.QRect(410, 100, 121, 16))
        self.user_id.setObjectName("user_id")
        self.frame_error_logged = QtWidgets.QFrame(self.content_3)
        self.frame_error_logged.setGeometry(QtCore.QRect(12, 12, 595, 40))
        self.frame_error_logged.setMaximumSize(QtCore.QSize(595, 40))
        self.frame_error_logged.setStyleSheet("background-color: rgb(255, 85, 127);\n"
"border-radius: 5px;")
        self.frame_error_logged.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error_logged.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error_logged.setObjectName("frame_error_logged")
        self.label_error_4 = QtWidgets.QLabel(self.frame_error_logged)
        self.label_error_4.setGeometry(QtCore.QRect(11, 11, 531, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_error_4.setFont(font)
        self.label_error_4.setStyleSheet("color: rgb(35, 35, 35);")
        self.label_error_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_4.setObjectName("label_error_4")
        self.pushButton_close_pupup_3 = QtWidgets.QPushButton(self.frame_error_logged)
        self.pushButton_close_pupup_3.setGeometry(QtCore.QRect(570, 10, 20, 20))
        self.pushButton_close_pupup_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_close_pupup_3.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;    \n"
"    background-image: url(Images/cil-x.png);\n"
"    background-position: center;    \n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.pushButton_close_pupup_3.setText("")
        self.pushButton_close_pupup_3.setObjectName("pushButton_close_pupup_3")
        self.stackedWidget.addWidget(self.accounts_page)
        self.passchange_page = QtWidgets.QWidget()
        self.passchange_page.setObjectName("passchange_page")
        self.content_4 = QtWidgets.QFrame(self.passchange_page)
        self.content_4.setGeometry(QtCore.QRect(150, 10, 667, 679))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content_4.sizePolicy().hasHeightForWidth())
        self.content_4.setSizePolicy(sizePolicy)
        self.content_4.setMinimumSize(QtCore.QSize(667, 679))
        self.content_4.setStyleSheet("")
        self.content_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_4.setObjectName("content_4")
        self.login_area_5 = QtWidgets.QFrame(self.content_4)
        self.login_area_5.setGeometry(QtCore.QRect(12, 59, 647, 608))
        self.login_area_5.setMaximumSize(QtCore.QSize(647, 641))
        self.login_area_5.setStyleSheet("border-radius: 10px;")
        self.login_area_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area_5.setObjectName("login_area_5")
        self.logo_5 = QtWidgets.QFrame(self.login_area_5)
        self.logo_5.setGeometry(QtCore.QRect(160, 60, 191, 90))
        self.logo_5.setStyleSheet("background-image: url(Images/useraccount.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.logo_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_5.setObjectName("logo_5")
        self.avatar_5 = QtWidgets.QFrame(self.login_area_5)
        self.avatar_5.setGeometry(QtCore.QRect(30, 50, 121, 121))
        self.avatar_5.setStyleSheet("QFrame {\n"
"    background-image: url(Images/avatar.png);\n"
"    border-radius: 60px;\n"
"    border: 10px solid rgb(255, 207, 0);\n"
"    background-position: center;\n"
"}\n"
"QFrame:hover {\n"
"    border: 10px solid rgb(255, 225, 0);\n"
"}\n"
"\n"
"")
        self.avatar_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.avatar_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.avatar_5.setObjectName("avatar_5")
        self.loggedUser_chpass = QtWidgets.QLineEdit(self.login_area_5)
        self.loggedUser_chpass.setEnabled(False)
        self.loggedUser_chpass.setGeometry(QtCore.QRect(180, 150, 391, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.loggedUser_chpass.setFont(font)
        self.loggedUser_chpass.setAutoFillBackground(False)
        self.loggedUser_chpass.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);        \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.loggedUser_chpass.setInputMask("")
        self.loggedUser_chpass.setText("")
        self.loggedUser_chpass.setMaxLength(32)
        self.loggedUser_chpass.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.loggedUser_chpass.setObjectName("loggedUser_chpass")
        self.changepassword_Btn = QtWidgets.QPushButton(self.login_area_5)
        self.changepassword_Btn.setGeometry(QtCore.QRect(180, 440, 281, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.changepassword_Btn.setFont(font)
        self.changepassword_Btn.setStyleSheet("QPushButton {    \n"
"\n"
"    background-color:rgb(255, 255, 127);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color:  rgb(239, 239, 239);\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.changepassword_Btn.setObjectName("changepassword_Btn")
        self.lineEdit_newPassword = QtWidgets.QLineEdit(self.login_area_5)
        self.lineEdit_newPassword.setGeometry(QtCore.QRect(180, 295, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_newPassword.setFont(font)
        self.lineEdit_newPassword.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_newPassword.setMaxLength(16)
        self.lineEdit_newPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_newPassword.setObjectName("lineEdit_newPassword")
        self.lineEdit_newPassword_confrm = QtWidgets.QLineEdit(self.login_area_5)
        self.lineEdit_newPassword_confrm.setGeometry(QtCore.QRect(180, 370, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_newPassword_confrm.setFont(font)
        self.lineEdit_newPassword_confrm.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_newPassword_confrm.setMaxLength(16)
        self.lineEdit_newPassword_confrm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_newPassword_confrm.setObjectName("lineEdit_newPassword_confrm")
        self.lineEdit_oldPassword = QtWidgets.QLineEdit(self.login_area_5)
        self.lineEdit_oldPassword.setGeometry(QtCore.QRect(180, 220, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_oldPassword.setFont(font)
        self.lineEdit_oldPassword.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_oldPassword.setMaxLength(16)
        self.lineEdit_oldPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_oldPassword.setObjectName("lineEdit_oldPassword")
        self.frame_error_chpass = QtWidgets.QFrame(self.content_4)
        self.frame_error_chpass.setGeometry(QtCore.QRect(12, 12, 595, 40))
        self.frame_error_chpass.setMaximumSize(QtCore.QSize(595, 40))
        self.frame_error_chpass.setStyleSheet("background-color: rgb(255, 85, 127);\n"
"border-radius: 5px;")
        self.frame_error_chpass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error_chpass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error_chpass.setObjectName("frame_error_chpass")
        self.label_error_5 = QtWidgets.QLabel(self.frame_error_chpass)
        self.label_error_5.setGeometry(QtCore.QRect(11, 11, 531, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_error_5.setFont(font)
        self.label_error_5.setStyleSheet("color: rgb(35, 35, 35);")
        self.label_error_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_5.setObjectName("label_error_5")
        self.pushButton_close_pupup_4 = QtWidgets.QPushButton(self.frame_error_chpass)
        self.pushButton_close_pupup_4.setGeometry(QtCore.QRect(570, 10, 20, 20))
        self.pushButton_close_pupup_4.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_close_pupup_4.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;    \n"
"    background-image: url(Images/cil-x.png);\n"
"    background-position: center;    \n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.pushButton_close_pupup_4.setText("")
        self.pushButton_close_pupup_4.setObjectName("pushButton_close_pupup_4")
        self.stackedWidget.addWidget(self.passchange_page)
        self.register_page = QtWidgets.QWidget()
        self.register_page.setObjectName("register_page")
        self.content_2 = QtWidgets.QFrame(self.register_page)
        self.content_2.setGeometry(QtCore.QRect(260, 10, 481, 611))
        self.content_2.setStyleSheet("")
        self.content_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_2.setObjectName("content_2")
        self.login_area_3 = QtWidgets.QFrame(self.content_2)
        self.login_area_3.setGeometry(QtCore.QRect(20, 60, 450, 550))
        self.login_area_3.setMaximumSize(QtCore.QSize(450, 550))
        self.login_area_3.setStyleSheet("border-radius: 10px;")
        self.login_area_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area_3.setObjectName("login_area_3")
        self.logo_3 = QtWidgets.QFrame(self.login_area_3)
        self.logo_3.setGeometry(QtCore.QRect(50, 20, 360, 90))
        self.logo_3.setStyleSheet("background-image: url(Images/register_360x90.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.logo_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_3.setObjectName("logo_3")
        self.avatar_3 = QtWidgets.QFrame(self.login_area_3)
        self.avatar_3.setGeometry(QtCore.QRect(160, 110, 120, 120))
        self.avatar_3.setStyleSheet("QFrame {\n"
"    background-image: url(Images/avatar.png);\n"
"    border-radius: 60px;\n"
"    border: 10px solid rgb(255, 207, 0);\n"
"    background-position: center;\n"
"}\n"
"QFrame:hover {\n"
"    border: 10px solid rgb(255, 225, 0);\n"
"}\n"
"\n"
"")
        self.avatar_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.avatar_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.avatar_3.setObjectName("avatar_3")
        self.lineEdit_Ruser = QtWidgets.QLineEdit(self.login_area_3)
        self.lineEdit_Ruser.setGeometry(QtCore.QRect(80, 240, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_Ruser.setFont(font)
        self.lineEdit_Ruser.setAutoFillBackground(False)
        self.lineEdit_Ruser.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);        \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_Ruser.setInputMask("")
        self.lineEdit_Ruser.setText("")
        self.lineEdit_Ruser.setMaxLength(32)
        self.lineEdit_Ruser.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_Ruser.setObjectName("lineEdit_Ruser")
        self.lineEdit_Rpassword = QtWidgets.QLineEdit(self.login_area_3)
        self.lineEdit_Rpassword.setGeometry(QtCore.QRect(80, 315, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_Rpassword.setFont(font)
        self.lineEdit_Rpassword.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_Rpassword.setMaxLength(16)
        self.lineEdit_Rpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Rpassword.setObjectName("lineEdit_Rpassword")
        self.RegisterBtn = QtWidgets.QPushButton(self.login_area_3)
        self.RegisterBtn.setGeometry(QtCore.QRect(80, 470, 280, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RegisterBtn.setFont(font)
        self.RegisterBtn.setStyleSheet("QPushButton {    \n"
"\n"
"    background-color:rgb(255, 255, 127);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color:  rgb(239, 239, 239);\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.RegisterBtn.setObjectName("RegisterBtn")
        self.lineEdit_Rpassword_confrm = QtWidgets.QLineEdit(self.login_area_3)
        self.lineEdit_Rpassword_confrm.setGeometry(QtCore.QRect(80, 390, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_Rpassword_confrm.setFont(font)
        self.lineEdit_Rpassword_confrm.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 207, 0);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_Rpassword_confrm.setMaxLength(16)
        self.lineEdit_Rpassword_confrm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Rpassword_confrm.setObjectName("lineEdit_Rpassword_confrm")
        self.Reg_login = QtWidgets.QPushButton(self.login_area_3)
        self.Reg_login.setGeometry(QtCore.QRect(100, 520, 270, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Reg_login.setFont(font)
        self.Reg_login.setStyleSheet("QPushButton { \n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover { \n"
"    color: rgb(255, 255, 127);\n"
"}")
        self.Reg_login.setObjectName("Reg_login")
        self.frame_error_reg = QtWidgets.QFrame(self.content_2)
        self.frame_error_reg.setGeometry(QtCore.QRect(20, 20, 450, 38))
        self.frame_error_reg.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_error_reg.setStyleSheet("background-color: rgb(255, 85, 127);\n"
"border-radius: 5px;")
        self.frame_error_reg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error_reg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error_reg.setObjectName("frame_error_reg")
        self.label_error_3 = QtWidgets.QLabel(self.frame_error_reg)
        self.label_error_3.setGeometry(QtCore.QRect(11, 11, 401, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_error_3.setFont(font)
        self.label_error_3.setStyleSheet("color: rgb(35, 35, 35);")
        self.label_error_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_3.setObjectName("label_error_3")
        self.pushButton_close_pupup_reg = QtWidgets.QPushButton(self.frame_error_reg)
        self.pushButton_close_pupup_reg.setGeometry(QtCore.QRect(419, 11, 20, 20))
        self.pushButton_close_pupup_reg.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_close_pupup_reg.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;    \n"
"    background-image: url(Images/cil-x.png);\n"
"    background-position: center;    \n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);    \n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);    \n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.pushButton_close_pupup_reg.setText("")
        self.pushButton_close_pupup_reg.setObjectName("pushButton_close_pupup_reg")
        self.stackedWidget.addWidget(self.register_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setStyleSheet("")
        self.settings_page.setObjectName("settings_page")
        self.label_4 = QtWidgets.QLabel(self.settings_page)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 781, 91))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(84, 84, 84);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.x_notes = QtWidgets.QWidget(self.settings_page)
        self.x_notes.setGeometry(QtCore.QRect(70, 130, 297, 266))
        self.x_notes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.x_notes.setAutoFillBackground(False)
        self.x_notes.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 125, 27);\n"
"    border-radius: 10px;\n"
"border:none\n"
"\n"
"}")
        self.x_notes.setObjectName("x_notes")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.x_notes)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.x_label = QtWidgets.QLabel(self.x_notes)
        self.x_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x_label.setFont(font)
        self.x_label.setStyleSheet("")
        self.x_label.setScaledContents(False)
        self.x_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_label.setWordWrap(True)
        self.x_label.setIndent(-1)
        self.x_label.setObjectName("x_label")
        self.verticalLayout_4.addWidget(self.x_label)
        self.x_line = QtWidgets.QFrame(self.x_notes)
        self.x_line.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.x_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.x_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.x_line.setObjectName("x_line")
        self.verticalLayout_4.addWidget(self.x_line)
        self.x_details_label = QtWidgets.QLabel(self.x_notes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_details_label.sizePolicy().hasHeightForWidth())
        self.x_details_label.setSizePolicy(sizePolicy)
        self.x_details_label.setMinimumSize(QtCore.QSize(275, 150))
        self.x_details_label.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x_details_label.setFont(font)
        self.x_details_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.x_details_label.setAutoFillBackground(False)
        self.x_details_label.setStyleSheet("")
        self.x_details_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.x_details_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.x_details_label.setLineWidth(1)
        self.x_details_label.setScaledContents(False)
        self.x_details_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_details_label.setWordWrap(False)
        self.x_details_label.setIndent(-2)
        self.x_details_label.setOpenExternalLinks(False)
        self.x_details_label.setObjectName("x_details_label")
        self.verticalLayout_4.addWidget(self.x_details_label)
        self.xpushButton = QtWidgets.QPushButton(self.x_notes)
        self.xpushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.xpushButton.setStyleSheet("QPushButton{\n"
"            background-color:rgba(85, 98, 112, 255);\n"
"            color:rgba(255, 255, 255, 200);\n"
"            border-radius:5px;\n"
"\n"
"        }\n"
"        QPushButton:pressed{\n"
"            padding-left:5px;\n"
"            padding-top:5px;\n"
"            background-color:rgba(255, 107, 107, 255);\n"
"            background-position:calc(100% - 10px)center;\n"
"        }\n"
"        QPushButton:hover{\n"
"            background-color:rgba(255, 107, 107, 255);\n"
"        }")
        self.xpushButton.setObjectName("xpushButton")
        self.verticalLayout_4.addWidget(self.xpushButton)
        self.stackedWidget.addWidget(self.settings_page)
        self.notes_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notes_page.sizePolicy().hasHeightForWidth())
        self.notes_page.setSizePolicy(sizePolicy)
        self.notes_page.setToolTipDuration(0)
        self.notes_page.setStyleSheet("")
        self.notes_page.setObjectName("notes_page")
        self.frame_3 = QtWidgets.QFrame(self.notes_page)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1321, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(80, 0, 841, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {text-align:center;\n"
"color:rgb(255, 207, 0);\n"
"\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.notes_page)
        self.newnote_page = QtWidgets.QWidget()
        self.newnote_page.setObjectName("newnote_page")
        self.widget = QtWidgets.QWidget(self.newnote_page)
        self.widget.setGeometry(QtCore.QRect(260, 130, 491, 531))
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(0, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("color:rgb(255, 207, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(20, 400, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("color:rgb(255, 207, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(8, 330, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("color:rgb(255, 207, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        self.dateEdit.setGeometry(QtCore.QRect(100, 390, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setAutoFillBackground(False)
        self.dateEdit.setStyleSheet("background-color:rgb(255, 255, 127);\n"
"border:none;")
        self.dateEdit.setWrapping(False)
        self.dateEdit.setFrame(True)
        self.dateEdit.setKeyboardTracking(True)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.priority_combo = QtWidgets.QComboBox(self.widget)
        self.priority_combo.setGeometry(QtCore.QRect(100, 330, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.priority_combo.setFont(font)
        self.priority_combo.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border:none;\n"
"\n"
"")
        self.priority_combo.setObjectName("priority_combo")
        self.priority_combo.addItem("")
        self.priority_combo.addItem("")
        self.priority_combo.addItem("")
        self.newnote_cancel = QtWidgets.QPushButton(self.widget)
        self.newnote_cancel.setGeometry(QtCore.QRect(100, 450, 181, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.newnote_cancel.setFont(font)
        self.newnote_cancel.setStyleSheet("QPushButton {    \n"
"\n"
"    background-color: rgb(255, 207, 0);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color:  rgb(239, 239, 239);\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.newnote_cancel.setObjectName("newnote_cancel")
        self.newnote_save = QtWidgets.QPushButton(self.widget)
        self.newnote_save.setGeometry(QtCore.QRect(290, 450, 181, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.newnote_save.setFont(font)
        self.newnote_save.setStyleSheet("QPushButton {    \n"
"\n"
"    background-color: rgb(255, 207, 0);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color:  rgb(239, 239, 239);\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.newnote_save.setObjectName("newnote_save")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(0, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("color:rgb(255, 207, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.note_content = QtWidgets.QPlainTextEdit(self.widget)
        self.note_content.setGeometry(QtCore.QRect(100, 80, 381, 231))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.note_content.setFont(font)
        self.note_content.setStyleSheet("    background-color:rgb(255, 255, 127);\n"
"    border-radius: 10px;\n"
"    border:none;\n"
"    padding-left:20px;")
        self.note_content.setPlainText("")
        self.note_content.setCenterOnScroll(True)
        self.note_content.setObjectName("note_content")
        self.title_text = QtWidgets.QLineEdit(self.widget)
        self.title_text.setGeometry(QtCore.QRect(100, 30, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title_text.setFont(font)
        self.title_text.setStyleSheet("    background-color:rgb(255, 255, 127);\n"
"    border-radius: 10px;\n"
"    border:none;\n"
"    padding-left:20px;")
        self.title_text.setObjectName("title_text")
        self.widget_2 = QtWidgets.QWidget(self.newnote_page)
        self.widget_2.setGeometry(QtCore.QRect(260, 50, 491, 80))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 207, 0);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.newnote_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.right_side_menu = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_side_menu.sizePolicy().hasHeightForWidth())
        self.right_side_menu.setSizePolicy(sizePolicy)
        self.right_side_menu.setMinimumSize(QtCore.QSize(0, 664))
        self.right_side_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.right_side_menu.setSizeIncrement(QtCore.QSize(0, 0))
        self.right_side_menu.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.right_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_side_menu.setObjectName("right_side_menu")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.right_side_menu)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout.addWidget(self.right_side_menu)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMinimumSize(QtCore.QSize(0, 40))
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 30))
        self.main_footer.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-top-color: solid 1px  rgb(0, 0, 0);\n"
"}\n"
"QLabel{\n"
"    color: #fff;\n"
"}")
        self.main_footer.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.main_footer)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.main_footer)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.verticalLayout.addWidget(self.main_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Notera"))
        self.accounts_button.setText(_translate("MainWindow", "ACCOUNT"))
        self.home_button.setText(_translate("MainWindow", "HOME"))
        self.notes_button.setText(_translate("MainWindow", "NOTES"))
        self.newnoteBtn.setText(_translate("MainWindow", "New Note"))
        self.settings_button.setText(_translate("MainWindow", "SETTINGS"))
        self.lineEdit_user.setPlaceholderText(_translate("MainWindow", "USER"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.checkBox_save_user.setText(_translate("MainWindow", "SAVE USER"))
        self.pushButton_login.setText(_translate("MainWindow", "L O G I N"))
        self.Login_reg.setText(_translate("MainWindow", "Not Registered? REGISTER"))
        self.label_error.setText(_translate("MainWindow", "Error"))
        self.loggedUser.setPlaceholderText(_translate("MainWindow", "USER"))
        self.logoutBtn.setText(_translate("MainWindow", "L O G  O U T"))
        self.changepasBtn.setText(_translate("MainWindow", "Change Password"))
        self.user_id.setText(_translate("MainWindow", "TextLabel"))
        self.label_error_4.setText(_translate("MainWindow", "USER LOGGED IN"))
        self.loggedUser_chpass.setPlaceholderText(_translate("MainWindow", "USER"))
        self.changepassword_Btn.setText(_translate("MainWindow", "C H A N G E   P A S S W O R D"))
        self.lineEdit_newPassword.setPlaceholderText(_translate("MainWindow", "NEW PASSWORD"))
        self.lineEdit_newPassword_confrm.setPlaceholderText(_translate("MainWindow", "CONFIRM PASSWORD"))
        self.lineEdit_oldPassword.setPlaceholderText(_translate("MainWindow", "OLD PASSWORD"))
        self.label_error_5.setText(_translate("MainWindow", "USER PASSWORD CHANGE"))
        self.lineEdit_Ruser.setPlaceholderText(_translate("MainWindow", "USER"))
        self.lineEdit_Rpassword.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.RegisterBtn.setText(_translate("MainWindow", "R E G I S T E R"))
        self.lineEdit_Rpassword_confrm.setPlaceholderText(_translate("MainWindow", "CONFIRM PASSWORD"))
        self.Reg_login.setText(_translate("MainWindow", "Already registered? LOGIN"))
        self.label_error_3.setText(_translate("MainWindow", "Error"))
        self.label_4.setText(_translate("MainWindow", "Setttings Page"))
        self.x_label.setText(_translate("MainWindow", "TextLabel"))
        self.x_details_label.setText(_translate("MainWindow", "TextLabel"))
        self.xpushButton.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "USER NOTES"))
        self.label_3.setText(_translate("MainWindow", "Note"))
        self.label_9.setText(_translate("MainWindow", "Date"))
        self.label_8.setText(_translate("MainWindow", "Priority"))
        self.priority_combo.setItemText(0, _translate("MainWindow", "1"))
        self.priority_combo.setItemText(1, _translate("MainWindow", "2"))
        self.priority_combo.setItemText(2, _translate("MainWindow", "3"))
        self.newnote_cancel.setText(_translate("MainWindow", "C A N C E L"))
        self.newnote_save.setText(_translate("MainWindow", "S A V E"))
        self.label_5.setText(_translate("MainWindow", "Title"))
        self.note_content.setPlaceholderText(_translate("MainWindow", "NOTE"))
        self.title_text.setPlaceholderText(_translate("MainWindow", "TITLE"))
        self.label_2.setText(_translate("MainWindow", "NEW NOTE"))
        self.label_7.setText(_translate("MainWindow", "v 1.0"))
import main_app_rc
